# Generated by Django 4.2.1 on 2023-05-27 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculeazaDurataTotalaVizionari',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('durataTotala', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalculeazaMediaRatingFilm',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('media', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CalculeazaSumaRatingFilm',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sumaRating', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VerificaVizionareFilm',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('exista', models.BooleanField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('ID_Film', models.IntegerField(primary_key=True, serialize=False)),
                ('Titlu', models.CharField(max_length=100, null=True)),
                ('Regizor', models.CharField(max_length=100, null=True)),
                ('An_Lansare', models.IntegerField(null=True)),
                ('Gen', models.CharField(max_length=50, null=True)),
                ('Rating_Mediu', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilizatori',
            fields=[
                ('ID_Utilizator', models.IntegerField(primary_key=True, serialize=False)),
                ('Nume_Utilizator', models.CharField(max_length=50, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('Parola', models.CharField(max_length=50, null=True)),
                ('Data_Inregistrare', models.DateField(null=True)),
                ('Durata_Totala_Vizionari', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vizionari_Filme',
            fields=[
                ('ID_Vizionare', models.IntegerField(primary_key=True, serialize=False)),
                ('Data_Vizionare', models.DateField(null=True)),
                ('Durata', models.IntegerField(null=True)),
                ('ID_Film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlist.filme')),
                ('ID_Utilizator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlist.utilizatori')),
            ],
        ),
        migrations.CreateModel(
            name='Rating_Filme',
            fields=[
                ('ID_Rating', models.IntegerField(primary_key=True, serialize=False)),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=3, null=True)),
                ('Data_Rating', models.DateField(null=True)),
                ('ID_Film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlist.filme')),
                ('ID_Utilizator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlist.utilizatori')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarii_Filme',
            fields=[
                ('ID_Comentariu', models.IntegerField(primary_key=True, serialize=False)),
                ('Comentariu', models.TextField(null=True)),
                ('Data_Comentariu', models.DateField(null=True)),
                ('ID_Film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlist.filme')),
                ('ID_Utilizator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlist.utilizatori')),
            ],
        ),
    ]
